from __future__ import annotations

import json
import os
from pathlib import Path
from typing import Any

import typer
from rich import print

from model_port.common.config import load_yaml
from model_port.registry.wandb_utils import (
    artifact_aliases,
    wandb_project,
    wandb_registry_target_path,
)

app = typer.Typer(help="Register model metadata to the W&B Model Registry.")


@app.command()
def main(
    manifest: Path = typer.Option(..., "--manifest", "-m", help="Model manifest YAML."),
    model_dir: Path | None = typer.Option(None, "--model-dir", help="Model artifact directory."),
    eval_report: Path = typer.Option(
        Path("artifacts/eval/eval_report.json"),
        "--eval-report",
        help="Evaluation report JSON generated by model_port.pipelines.evaluate.",
    ),
    aliases: str | None = typer.Option(
        None,
        "--aliases",
        help="Comma-separated W&B artifact aliases. Defaults are derived from quality gate results.",
    ),
    dry_run: bool = False,
) -> None:
    data = load_yaml(manifest)
    model = data["model"]
    name = f"{model['vendor']}.{model['name']}"
    registry_name = os.getenv("WANDB_REGISTRY_NAME", "Model")
    collection = os.getenv("WANDB_REGISTRY_COLLECTION", model["name"])
    artifact_type = os.getenv("WANDB_ARTIFACT_TYPE", "model")
    target_path = wandb_registry_target_path(collection, registry_name)
    entity = os.getenv("WANDB_ENTITY", "").strip()
    report = _load_eval_report(eval_report)
    metadata = _artifact_metadata(data, report)
    aliases_for_artifact = _parse_aliases(aliases) or artifact_aliases(model["version"], report)

    if dry_run:
        print("[yellow]Dry run W&B registration[/yellow]")
        print({
            "registered_model_name": name,
            "registry_name": registry_name,
            "collection": collection,
            "target_path": target_path,
            "artifact_type": artifact_type,
            "entity": entity or None,
            "artifact_uri": str(model_dir or model["artifact_uri"]),
            "aliases": aliases_for_artifact,
            "metadata": metadata,
        })
        return

    if not entity:
        raise typer.BadParameter(
            "WANDB_ENTITY must be set to a W&B team/entity before linking to the "
            "Registry. W&B does not link personal-entity artifacts into Registry "
            "collections. For W&B Local, create or select a team in the UI, set "
            "WANDB_ENTITY=<team_entity> in .env, then recreate the trainer."
        )

    import wandb

    run = wandb.init(
        entity=entity,
        project=wandb_project(data),
        job_type="registry",
        name=f"register-{name}-{model['version']}",
        tags=["registry", model["vendor"], model["task"]],
    )
    try:
        artifact = wandb.Artifact(
            name=name.replace(".", "-"),
            type=artifact_type,
            metadata=metadata,
        )
        artifact.add_file(str(manifest), name="model_manifest.yaml")
        if eval_report.exists():
            artifact.add_file(str(eval_report), name="eval_report.json")

        artifact_dir = model_dir or Path(model["artifact_uri"])
        if artifact_dir.is_dir():
            artifact.add_dir(str(artifact_dir))

        linked = run.link_artifact(
            artifact=artifact,
            target_path=target_path,
            aliases=aliases_for_artifact,
        )
        if linked is not None:
            linked.wait()
        print(
            f"[green]Registered {name}:{model['version']} in W&B registry "
            f"{registry_name}/{collection}[/green]"
        )
    finally:
        run.finish()


def _load_eval_report(path: Path) -> dict[str, Any] | None:
    if not path.exists():
        return None
    return json.loads(path.read_text(encoding="utf-8"))


def _artifact_metadata(data: dict[str, Any], report: dict[str, Any] | None) -> dict[str, Any]:
    model = data["model"]
    metadata: dict[str, Any] = {
        "vendor": model["vendor"],
        "model_name": model["name"],
        "model_version": model["version"],
        "task": model["task"],
        "stage": data["deployment"].get("stage", "candidate"),
        "artifact_uri": model["artifact_uri"],
    }
    if not report:
        return metadata

    metrics = report.get("metrics", {})
    gate = report.get("quality_gate", {})
    metadata.update({
        "quality_gate_profile": gate.get("profile"),
        "quality_gate_passed": bool(gate.get("passed")),
        "reject_reason": gate.get("reject_reason"),
        "p95_latency_ms": metrics.get("p95_latency_ms"),
        "max_p95_latency_ms": gate.get("max_p95_latency_ms"),
        "model_size_mb": metrics.get("model_size_mb"),
        "max_model_size_mb": gate.get("max_model_size_mb"),
        "drift_score": metrics.get("drift_score"),
        "failure_rate": metrics.get("failure_rate"),
    })
    return metadata


def _parse_aliases(aliases: str | None) -> list[str]:
    if not aliases:
        return []
    return [alias.strip() for alias in aliases.split(",") if alias.strip()]


if __name__ == "__main__":
    app()
