from __future__ import annotations

import json
import os
from pathlib import Path
from typing import Any

import typer
from rich import print

from model_port.common.config import load_yaml
from model_port.registry.wandb_utils import wandb_project

app = typer.Typer(help="Register model metadata to the W&B Model Registry.")


@app.command()
def main(
    manifest: Path = typer.Option(..., "--manifest", "-m", help="Model manifest YAML."),
    model_dir: Path | None = typer.Option(None, "--model-dir", help="Model artifact directory."),
    eval_report: Path = typer.Option(
        Path("artifacts/eval/eval_report.json"),
        "--eval-report",
        help="Evaluation report JSON generated by model_port.pipelines.evaluate.",
    ),
    aliases: str | None = typer.Option(
        None,
        "--aliases",
        help="Comma-separated W&B artifact aliases. Defaults are derived from quality gate results.",
    ),
    dry_run: bool = False,
) -> None:
    data = load_yaml(manifest)
    model = data["model"]
    name = f"{model['vendor']}.{model['name']}"
    collection = os.getenv("WANDB_REGISTRY_COLLECTION", model["name"])
    report = _load_eval_report(eval_report)
    metadata = _artifact_metadata(data, report)
    artifact_aliases = _parse_aliases(aliases) or _artifact_aliases(model["version"], report)

    if dry_run:
        print("[yellow]Dry run W&B registration[/yellow]")
        print({
            "registered_model_name": name,
            "artifact_uri": str(model_dir or model["artifact_uri"]),
            "aliases": artifact_aliases,
            "metadata": metadata,
        })
        return

    import wandb

    run = wandb.init(
        project=wandb_project(data),
        job_type="registry",
        name=f"register-{name}-{model['version']}",
        tags=["registry", model["vendor"], model["task"]],
    )
    try:
        artifact = wandb.Artifact(
            name=name.replace(".", "-"),
            type="model",
            metadata=metadata,
        )
        artifact.add_file(str(manifest), name="model_manifest.yaml")
        if eval_report.exists():
            artifact.add_file(str(eval_report), name="eval_report.json")

        artifact_dir = model_dir or Path(model["artifact_uri"])
        if artifact_dir.is_dir():
            artifact.add_dir(str(artifact_dir))

        logged = run.log_artifact(artifact, aliases=artifact_aliases)
        logged.wait()

        # Link into the W&B Model Registry so it shows up as a managed collection.
        run.link_artifact(logged, target_path=f"wandb-registry-model/{collection}")
        print(f"[green]Registered {name}:{model['version']} in W&B registry[/green]")
    finally:
        run.finish()


def _load_eval_report(path: Path) -> dict[str, Any] | None:
    if not path.exists():
        return None
    return json.loads(path.read_text(encoding="utf-8"))


def _artifact_metadata(data: dict[str, Any], report: dict[str, Any] | None) -> dict[str, Any]:
    model = data["model"]
    metadata: dict[str, Any] = {
        "vendor": model["vendor"],
        "model_name": model["name"],
        "model_version": model["version"],
        "task": model["task"],
        "stage": data["deployment"].get("stage", "candidate"),
        "artifact_uri": model["artifact_uri"],
    }
    if not report:
        return metadata

    metrics = report.get("metrics", {})
    gate = report.get("quality_gate", {})
    metadata.update({
        "quality_gate_profile": gate.get("profile"),
        "quality_gate_passed": bool(gate.get("passed")),
        "reject_reason": gate.get("reject_reason"),
        "p95_latency_ms": metrics.get("p95_latency_ms"),
        "max_p95_latency_ms": gate.get("max_p95_latency_ms"),
        "model_size_mb": metrics.get("model_size_mb"),
        "max_model_size_mb": gate.get("max_model_size_mb"),
        "drift_score": metrics.get("drift_score"),
        "failure_rate": metrics.get("failure_rate"),
    })
    return metadata


def _artifact_aliases(version: str, report: dict[str, Any] | None) -> list[str]:
    version_alias = f"v{version}"
    aliases = ["candidate"]
    if not report:
        return [*aliases, version_alias]

    gate = report.get("quality_gate", {})
    if gate.get("passed"):
        aliases.append("passed")
        aliases.append(version_alias)
        return aliases

    reject_reason = gate.get("reject_reason")
    if reject_reason == "p95_latency_ms_exceeded":
        aliases.append("rejected-latency")
    elif reject_reason:
        aliases.append(f"rejected-{str(reject_reason).replace('_exceeded', '').replace('_', '-')}")
    else:
        aliases.append("rejected")
    aliases.append(version_alias)
    return aliases


def _parse_aliases(aliases: str | None) -> list[str]:
    if not aliases:
        return []
    return [alias.strip() for alias in aliases.split(",") if alias.strip()]


if __name__ == "__main__":
    app()
